export const PROCESSING_STEPS = {
  UPLOADED: "UPLOADED",
  TRANSCRIBING: "TRANSCRIBING",
  DIARIZING: "DIARIZING",
  ANALYZING: "ANALYZING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
} as const;